### ISSUE TITLE
CORS Error when refreshing from http://ismytraindelayed.today

### ISSUE THREAD

**Issue by danieldafoe** [danieldafoe/is-my-train-delayed#13]
Since the domain-less ismytraindelayed.today really just redirects to is-my-train-delayed.herokuapp.com, there's a cross-origin issue.

**Comment by danieldafoe** [comment]
Looking into solving this with an ExpressJS middleware function, but it hasn't worked in my testing so far.

**Comment by emctague** [comment]
Hello @danieldafoe, I have found what I believe is a solution to this bug. I can submit a pull request containing the change, if you would like.
