### ISSUE TITLE
Remove Duplicate Retreival Code

### ISSUE THREAD

**Issue by emctague** [danieldafoe/is-my-train-delayed#19]
I have forked this project, and am working on eliminating redundant / duplicate retrieval code (the identical train info fetching calls) from `server.js`. I am also changing `app.js` to use the relative url `/fetch` - so that reloading can be tested on instances other than the live, production app.

**Comment by danieldafoe** [comment]
Fixed by 567cc9b25f8944fd872999ce5a767fef6a929100 .
