### ISSUE TITLE
Allow auto-fetch of train information

### ISSUE THREAD

**Issue by danieldafoe** [danieldafoe/is-my-train-delayed#3]
App should allow you to choose how often you want to fetch for new data. This should obviously be done via AJAX.

Will likely implement with React.

**Comment by danieldafoe** [comment]
Auto-fetch is a possibility, but perhaps only by selecting a checkbox for how frequently you want the page to update itself.

**Comment by graypegg** [comment]
Could be done with web sockets! The server already does the data scraping, so formatting it to send only what's changed to all clients via a websocket shouldn't be too hard to implement.

**Comment by danieldafoe** [comment]
Good idea, @toish . I'm reluctant to implement this feature because I don't want to hit the GO Transit website with too many requests.
