### ISSUE TITLE
Create error page

### ISSUE THREAD

**Issue by danieldafoe** [danieldafoe/is-my-train-delayed#4]
Need to handle HTTP errors since Heroku allows custom error pages.

**Comment by graypegg** [comment]
Should be able to just use express to return HTTP errors:

https://expressjs.com/en/guide/error-handling.html

**Comment by danieldafoe** [comment]
You betcha. Thanks for the URL!

**Comment by danieldafoe** [comment]
Will push this tomorrow.

**Comment by danieldafoe** [comment]
Referenced by 5aa9ef76fb1ce67e96a6b0b082e15949ef106b4a .
